add oled esp pico d4, ADC changued
kike-canaries/canairio_firmware pull request #208
Opened 2022-02-25 13:22 UTC by roberbike

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR.

2022-02-25 23:59 UTC, hpsaturn requested changes

2022-02-25 23:59 UTC, hpsaturn commented on lib/batterylib/battery_oled.cpp
> +    // curv = ((float)v / 4095.0) * 16;
please remove unnecessary comments

2022-02-25 23:59 UTC, hpsaturn commented on lib/batterylib/battery_oled.cpp
>      // return curv;
please remove unnecessary comments

2022-02-26 09:05 UTC, roberbike commented on lib/batterylib/battery_oled.cpp
> +    // curv = ((float)v / 4095.0) * 16;
Done

2022-02-26 09:05 UTC, roberbike commented on lib/batterylib/battery_oled.cpp
>      // return curv;
Done

2022-02-26 09:29 UTC, merged